### ISSUE TITLE
0.0.4: build fails

### ISSUE THREAD

**Issue by kloczek** [intel/intel-lpmd#32] opened 2024-06-12 07:58 UTC
Looks like something is wrong with new 0.0.4
```console
[tkloczko@pers-jacek intel-lpmd-0.0.4]$ make -k
make  all-recursive
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/intel-lpmd-0.0.4'
Making all in data
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/intel-lpmd-0.0.4/data'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/intel-lpmd-0.0.4/data'
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/intel-lpmd-0.0.4'
  CC       src/intel_lpmd-lpmd_proc.o
src/lpmd_proc.c: In function ‘lpmd_core_main_loop’:
src/lpmd_proc.c:851:31: error: suggest parentheses around arithmetic in operand of ‘|’ [-Werror=parentheses]
  851 |                 if (lpm_state & (LPM_USER_ON | LPM_USER_OFF | LPM_SUV_ON) | has_hfi_lpm_monitor ())
      |                     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:723: src/intel_lpmd-lpmd_proc.o] Error 1
  CC       src/intel_lpmd-lpmd_cpu.o
src/lpmd_cpu.c: In function ‘set_epp’:
src/lpmd_cpu.c:567:13: error: unused variable ‘epp’ [-Werror=unused-variable]
  567 |         int epp;
      |             ^~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:765: src/intel_lpmd-lpmd_cpu.o] Error 1
  CC       src/intel_lpmd-lpmd_irq.o
src/lpmd_irq.c: In function ‘irqbalance_ban_cpus’:
src/lpmd_irq.c:137:13: error: unused variable ‘first’ [-Werror=unused-variable]
  137 |         int first = 1;
      |             ^~~~~
src/lpmd_irq.c:135:13: error: unused variable ‘cpu’ [-Werror=unused-variable]
  135 |         int cpu;
      |             ^~~
src/lpmd_irq.c: At top level:
src/lpmd_irq.c:95:12: error: ‘dump_smp_affinity’ defined but not used [-Werror=unused-function]
   95 | static int dump_smp_affinity(void)
      |            ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:807: src/intel_lpmd-lpmd_irq.o] Error 1
  CC       src/intel_lpmd-lpmd_util.o
src/lpmd_util.c: In function ‘parse_proc_stat’:
src/lpmd_util.c:101:13: error: unused variable ‘pos’ [-Werror=unused-variable]
  101 |         int pos = 0;
      |             ^~~
src/lpmd_util.c: In function ‘util_init’:
src/lpmd_util.c:512:16: error: unused variable ‘size’ [-Werror=unused-variable]
  512 |         size_t size;
      |                ^~~~
cc1: all warnings being treated as errors
```

**Comment by zhang-rui** [comment] 2024-06-12 08:01
how do you trigger this?
I cannot reproduce on my side.

**Comment by kloczek** [comment] 2024-06-12 08:03
There are more such errors about unused variables and functions (I've updated output).
I'm using gcc 14.1.0.

**Comment by zhang-rui** [comment] 2024-06-12 08:03
And please remove the line "int epp;" in set_epp() and check if the problem still exist.
This is a warning of unused variable, I'm wondering why I didn't see this warning at all.

**Comment by kloczek** [comment] 2024-06-12 08:04
In configure.ac is
``
AC_ARG_ENABLE(werror, AS_HELP_STRING([--disable-werror], [Disable -Werror]))
AS_IF([test "x$enable_werror" != "xno"], [CFLAGS="$CFLAGS -Werror"])
```
So by default all warnings are flipped into errors.

**Comment by zhang-rui** [comment] 2024-06-12 08:05
thanks for catching these.
Let me find a way to trigger this, or can you help send a PR for these cleanups?

**Comment by kloczek** [comment] 2024-06-12 08:06
Sorry have no time as I have very long list of other packages to update today 😞

**Comment by zhang-rui** [comment] 2024-06-12 08:07
NO. Let me try to reproduce on my side.
And thanks again for catching this!

**Comment by Yujie-Liu** [comment] 2024-06-12 09:54
Hi @kloczek, we can only reproduce this issue by adding extra CFLAGS to the make command.
```
# gcc-14 --version
gcc-14 (Debian 14.1.0-1) 14.1.0

intel-lpmd# make CC=gcc-14 CFLAGS="-Wunused-variable"
...
make[2]: Entering directory '/root/intel-lpmd'
  CC       tools/intel_lpmd_control-intel_lpmd_control.o
  CCLD     intel_lpmd_control
  CC       src/intel_lpmd-lpmd_main.o
  CC       src/intel_lpmd-lpmd_proc.o
  CC       src/intel_lpmd-lpmd_dbus_server.o
  CC       src/intel_lpmd-lpmd_config.o
  CC       src/intel_lpmd-lpmd_cpu.o
src/lpmd_cpu.c: In function 'set_epp':
src/lpmd_cpu.c:567:13: warning: unused variable 'epp' [-Wunused-variable]
  567 |         int epp;
      |             ^~~
```

Could you please share the output of "make V=1" on your side so we can further check the details of the gcc command? Thanks.
```
intel-lpmd# make V=1 CC=gcc-14
...
gcc-14 -DHAVE_CONFIG_H -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -pthread  -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -pthread  -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26     -I/usr/include/libxml2  -I/usr/include/libnl3  -I/usr/include/libnl3  -DGLIB_SUPPORT -DTDCONFDIR=\"/usr/local/etc/intel_lpmd\" -DTDLOCALEDIR=\"/usr/local/share/locale\" -DTDRUNDIR=\"/intel_lpmd\" -I./src  -I./src -g -O2 -Werror -MT src/intel_lpmd-lpmd_cpu.o -MD -MP -MF src/.deps/intel_lpmd-lpmd_cpu.Tpo -c -o src/intel_lpmd-lpmd_cpu.o `test -f 'src/lpmd_cpu.c' || echo './'`src/lpmd_cpu.c
...
```

**Comment by kloczek** [comment] 2024-06-12 09:58
So looks like you've configured source tree with --disable-werror which is not default
```console
[tkloczko@pers-jacek intel-lpmd-0.0.4]$ ./configure --help |grep error
  --disable-werror        Disable -Werror
```

**Comment by kloczek** [comment] 2024-06-12 10:03
FYI I'm not passing in env variables on packaging only `-Wall`.
```console
[tkloczko@pers-jacek SPECS]$ rpm -E %set_build_flags | grep ^CFLAGS
CFLAGS="-m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -g -grecord-gcc-switches -pipe -mtls-dialect=gnu2 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fdata-sections -ffunction-sections -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -flto=auto -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Werror=format-security";
```

**Comment by zhang-rui** [comment] 2024-06-12 13:51
I have pushed a fix, can you help check if the staging branch works well?

**Comment by kloczek** [comment] 2024-06-12 19:26
One sec 😋

**Comment by kloczek** [comment] 2024-06-12 19:28
Hmm but https://github.com/intel/intel-lpmd/compare/v0.0.4...main shows empty list 🤔

**Comment by vient** [comment] 2024-06-12 22:21
For me build fails with another error
```
  CC       src/intel_lpmd-lpmd_config.o
src/lpmd_config.c: In function ‘lpmd_get_config’:
src/lpmd_config.c:415:54: error: ‘%s’ directive output truncated writing 21 bytes into a region of size 13 [-Werror=format-truncation=]
  415 |         snprintf (file_name, MAX_FILE_NAME_PATH, "%s/%s", TDCONFDIR, CONFIG_FILE_NAME);
      |                                                      ^~
In file included from /usr/include/stdio.h:980,
                 from src/lpmd.h:23,
                 from src/lpmd_config.c:21:
In function ‘snprintf’,
    inlined from ‘lpmd_get_config’ at src/lpmd_config.c:415:2:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:54:10: note: ‘__builtin___snprintf_chk’ output 73 bytes into a destination of size 64
```

**Comment by zhang-rui** [comment] 2024-06-13 01:25
> Hmm but [v0.0.4...main](https://github.com/intel/intel-lpmd/compare/v0.0.4...main) shows empty list 🤔

the fix is in the -stable branch.
Let me push it to main branch anyway.

**Comment by zhang-rui** [comment] 2024-06-13 01:26
> So looks like you've configured source tree with --disable-werror which is not default
> 
> ```
> [tkloczko@pers-jacek intel-lpmd-0.0.4]$ ./configure --help |grep error
>   --disable-werror        Disable -Werror
> ```

No, I didn't do that.
I see you use "-Wall" and I can reproduce these failures with that added to Makefile manually.

**Comment by zhang-rui** [comment] 2024-06-13 01:47
> For me build fails with another error
> 
> ```
>   CC       src/intel_lpmd-lpmd_config.o
> src/lpmd_config.c: In function ‘lpmd_get_config’:
> src/lpmd_config.c:415:54: error: ‘%s’ directive output truncated writing 21 bytes into a region of size 13 [-Werror=format-truncation=]
>   415 |         snprintf (file_name, MAX_FILE_NAME_PATH, "%s/%s", TDCONFDIR, CONFIG_FILE_NAME);
>       |                                                      ^~
> In file included from /usr/include/stdio.h:980,
>                  from src/lpmd.h:23,
>                  from src/lpmd_config.c:21:
> In function ‘snprintf’,
>     inlined from ‘lpmd_get_config’ at src/lpmd_config.c:415:2:
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:54:10: note: ‘__builtin___snprintf_chk’ output 73 bytes into a destination of size 64
> ```

I cannot reproduce this even with "-Wall" appended.
But anyway, please help check the latest main branch to see if the problem still exists.

And BTW, can you share your output with "make V=1"?

**Comment by Yujie-Liu** [comment] 2024-06-13 02:19
> FYI I'm not passing in env variables on packaging only `-Wall`.
> 
> ```
> [tkloczko@pers-jacek SPECS]$ rpm -E %set_build_flags | grep ^CFLAGS
> CFLAGS="-m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -g -grecord-gcc-switches -pipe -mtls-dialect=gnu2 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fdata-sections -ffunction-sections -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -flto=auto -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Werror=format-security";
> ```

Hi @kloczek, it only shows very simple CFLAGS in my env.
```
$ rpm -E %set_build_flags | grep CFLAGS
  CFLAGS="${CFLAGS:--O2 -g}" ; export CFLAGS ;
```
I can reproduce the build failure if I manually add "-Wall" to CFLAGS.
May I know which distribution you are using? Is the long CFLAGS the default setting in your system?

BTW, it would still be helpful to see your output of "make V=1". Thanks.

**Comment by kloczek** [comment] 2024-06-13 12:58
OK just tested 0.0.4 + 4 patches generated from commits on top of last tag and looks like I was able to build and pass test suite.
Thank you.
Feel free to close this ticket if you have nothing more on your outstanding list.

**Comment by zhang-rui** [comment] 2024-06-13 13:44
Thanks, @kloczek .

BTW, can you have a check at this issue https://github.com/intel/intel-lpmd/issues/35?

**Closed** 2024-06-13 13:44 UTC

**Comment by zhang-rui** [comment] 2024-06-13 14:21
You should not apply that patch, but revert that one instead.
what I would do is
1. git clone https://github.com/intel/intel-lpmd.git
2. git revert 08b50e4c7bbe9bd50537d90ea9b621a0e973579c
